ALTER TABLE users
ADD COLUMN preferred_language VARCHAR(50) NOT NULL DEFAULT '',
ADD COLUMN date_of_birth DATE NULL,
ADD COLUMN gender VARCHAR(30) NOT NULL DEFAULT '',
ADD COLUMN avatar VARCHAR(255) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS user_preferences (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  promotional_emails TINYINT(1) NOT NULL DEFAULT 1,
  catalog_emails TINYINT(1) NOT NULL DEFAULT 1,
  birthday_discount_emails TINYINT(1) NOT NULL DEFAULT 1,
  order_updates TINYINT(1) NOT NULL DEFAULT 1,
  sms_notifications TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user_preferences_user (user_id)
);

CREATE TABLE IF NOT EXISTS user_payment_methods (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  cardholder_name VARCHAR(150) NOT NULL,
  card_brand VARCHAR(50) NOT NULL,
  last4 VARCHAR(4) NOT NULL,
  expiry_month VARCHAR(2) NOT NULL,
  expiry_year VARCHAR(4) NOT NULL,
  billing_method VARCHAR(100) NOT NULL,
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_user_payment_methods_user (user_id)
);

CREATE TABLE IF NOT EXISTS wishlist_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  product_id INT UNSIGNED NULL,
  sku VARCHAR(100) NOT NULL DEFAULT '',
  name VARCHAR(255) NOT NULL DEFAULT '',
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  image_path VARCHAR(255) NOT NULL DEFAULT '',
  size VARCHAR(50) NOT NULL DEFAULT '',
  color VARCHAR(50) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_wishlist_items_user (user_id)
);

CREATE TABLE IF NOT EXISTS customer_designs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT '',
  product_name VARCHAR(255) NOT NULL DEFAULT '',
  preview_image VARCHAR(255) NOT NULL DEFAULT '',
  project_url VARCHAR(255) NOT NULL DEFAULT '',
  project_data LONGTEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_customer_designs_user (user_id)
);